meta_product_name: "The Leap"
meta_title: "Leap - Love your layover"
meta_description: "Leap is a -tour operator that provides unique experiences specifically tailored to airport passangers"
meta_image: "leap-logo.png"

